homeassistant:
  # customize: !include customize.yaml
  packages: !include_dir_named packages

http:
#  ssl_certificate: !secret ssl_certificate
#  ssl_key: !secret ssl_key

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/scheduler-card/scheduler-card.js
      type: module

# Disable default config, selectively enable services needed.
# default_config:

# automation:
# cloud:
# config:
# discovery:
frontend:
history:
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
logbook:
# map:
mobile_app:
# person
# scene
# Script
# sspd:
sun:
system_health:
# updater:
# zeroconf:
# zone

tts:
  - platform: google_translate

logger:
  default: info
  logs:
    custom_components.atlas_scientific.sensor: debug
    custom_components.scheduler: debug
    homeassistant.components.switch.command_line: debug
    zeroconf: error
    homeassistant.components.websocket_api.http.connection: error

group: !include groups.yaml

# emulated_hue:
# listen_port: 80
#  expose_by_default: false
#  entities:
#    switch.pump:
#      name: Pump
#      hidden: false
#    switch.ph:
#      name: Acid Pump
#      hidden: false
#    switch.orp:
#      name: Chlorine Pump
#      hidden: false
#    switch.turbo:
#      name: Turbo
#      hidden: false

script: !include scripts.yaml

shell_command:
  calibrate: 'python calibrate.py "{{ device }}" "{{ target }}"'

system_log:
   max_entries: 500
