sensor:
  - platform: atlas_scientific
# For serial ports use:
#   port: /dev/ttyUSB0
# For I2C enter the hex device id
    port: /dev/ttySC0
#    offset: 78
    scan_interval: 600
    # never scan, scanning happens every 2 mins
    # *while the pump is on*

  - platform: statistics
    name: orp_stat
    entity_id: sensor.ezo_orp
    max_age:
      minutes: 60
    precision: 0

  - platform: template
    sensors:
      orp:
        unit_of_measurement: 'mV'
        value_template: >
          {% if is_state('sensor.orp_stat', 'unknown') %}
            0
          {% else %}
            {{ states('sensor.orp_stat') }}
          {% endif %}

input_number:
  calibrate_orp:
    min: 100
    max: 1500
    step: 1
    unit_of_measurement: 'mV'
    icon: mdi:water-percent
    mode: box
    initial: 700

automation:
  - alias: orp_start
    trigger:
    - platform: state
      entity_id: switch.orp
      to: 'on'
    condition:
    - condition: state
      entity_id: switch.pump
      state: 'off'
    action:
    - service: switch.turn_off
      entity_id: switch.orp

  - alias: orp_bad
    trigger:
    - platform: template
      value_template: '{{state_attr("sensor.orp", "standard_deviation") > 20 }}'
    condition: []
    action:
    - service: notify.notify
      data_template:
        message: 'It varied between {{state_attr("sensor.orp", "min_value")}} and 
          {{state_attr("sensor.orp", "max_value")}} over the past 
          {{(state_attr("sensor.orp", "sampling_size")*30/60)|int}} minutes'
          # scan_interval: 30 is the scan_interval for the orp probe (orp.yaml) 
        title: 'ORP probe may need calibration!'
    - service: automation.turn_off
      entity_id: automation.orp_bad
