input_datetime:
  cycle_start:
    name: Pump cycle start time
    has_date: false
    has_time: true
  recirculation:
    name: Recirculation cycle
    has_time: true
    has_date: false
    icon: mdi:timer-outline


input_number:
  capacity_imperial:
    name: Pool Capacity (gal)
    min: 1000
    max: 50000
    step: 1000
    unit_of_measurement: gal
    icon: mdi:water-pump
    mode: box
  capacity_metric:
    name: Pool Capacity (m³)
    min: 5
    max: 100
    unit_of_measurement: m³
    icon: mdi:water-pump
    mode: box
  quality:
    name: Water Quality
    min: 0
    max: 9
    unit_of_measurement: stars
    icon: mdi:star
  turbo:
    name: '% in high speed'
    min: 0
    max: 100
    step: 5
    unit_of_measurement: '%'
    icon: mdi:circle-slice-2

input_boolean:
  turbo:
    name: Dual-speed Pump
    icon: mdi:car-turbocharger
  
  factory_started:
    name: Factory config started
    icon: mdi:auto-fix

# should we use imperial units or metric?
# see issue #1
  imperial:
    name: Imperial Units
    icon: mdi:tape-measure
    initial: false

  salt_system:
    name: Salt System
    icon: mdi:shaker-outline
    initial: false

  has_flow_sensor:
    name: Flow sensor present
    initial: false

sensor:
  - platform: template
    sensors:
      simple_date:
        friendly_name: "Date"
        unique_id: sensordatetemplate
        value_template: >-
          {% if is_state("input_boolean.imperial", "on") %}
            {{as_timestamp(now()) | timestamp_custom('%m/%d')}}
          {% else %}
            {{as_timestamp(now()) | timestamp_custom('%d.%m.')}}
          {% endif %}
      simple_time:
        friendly_name: "Time"
        unique_id: sensortimetemplate
        value_template: "{{as_timestamp(now()) | timestamp_custom('%H:%M')}}"

automation:
  # Sync Pool Capacity (m3 vs gal)
  - alias: capacity_sync_1
    trigger:
      - platform: state
        entity_id: input_number.capacity_metric
    condition: []
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.capacity_imperial
          value: "{{(states('input_number.capacity_metric')|float * 264.172)| round(1) }}"

  - alias: capacity_sync_2
    trigger:
      - platform: state
        entity_id: input_number.capacity_imperial
    condition: []
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.capacity_metric
          value: "{{(states('input_number.capacity_imperial')|float / 264.172)| round(1) }}"

  - alias: factory_started
    trigger:
      platform: homeassistant
      event: start
    condition:
      condition: state
      entity_id: input_boolean.factory_started
      state: 'off'
    action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.factory_started
    - service: input_number.set_value
      data_template:
        entity_id: input_number.capacity_metric
        value: 50
    - service: input_number.set_value
      data_template:
        entity_id: input_number.quality
        value: 4
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bleach_tank
        value: 20
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bleach_concentration
        value: 5
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bleach_speed
        value: 25
    - service: input_number.set_value
      data_template:
        entity_id: input_number.fc_target
        value: 1.5
    - service: input_number.set_value
      data_template:
        entity_id: input_number.e_fc_adjust
        value: 0
    - service: input_number.set_value
      data_template:
        entity_id: input_number.ph_target
        value: 7.2
    - service: input_number.set_value
      data_template:
        entity_id: input_number.muriatic_tank
        value: 10
    - service: input_number.set_value
      data_template:
        entity_id: input_number.muriatic_concentration
        value: 20
    - service: input_number.set_value
      data_template:
        entity_id: input_number.muriatic_speed
        value: 25
    - service: input_datetime.set_datetime
      data_template:
        entity_id: input_datetime.recirculation
        time: 08:00:00
